name: 'Pull Request Target Branch Action'
description: 'A action to check that a PR''s target branch is correct, changing it if required'

inputs:
  target:
    description: 'The target branch'
    required: true

  change-to:
    description: 'The branch the PR''s target should be changed to if the target is incorrect'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'
  color: 'orange'
